### ISSUE TITLE
[Bug]全局变量引起的卡顿和相关bug

### ISSUE THREAD

**Issue by MCBBC** [koishijs/koishi-plugin-blockly#18]
当前问题：代码块过多导致卡顿
详细内容：移动整个工作区偶尔卡顿，移动整体代码块偶尔卡顿，代码块修改额外选项卡顿

可能原因：
![QQ图片20230209193052](https://user-images.githubusercontent.com/10040290/217801888-9a841ab4-5ac3-4b5f-8cf4-1794d6c0e280.png)

**Comment by TimeBather** [comment]
为使用的第三方库的问题,已向上游提交Issue:
mit-cml/blockly-plugins#29

**Comment by TimeBather** [comment]
上游已经推送新版本，下个正式版会修复

**Comment by TimeBather** [comment]
fixed
