### ISSUE TITLE
[Bug]缩放导致的问题

### ISSUE THREAD

**Issue by MCBBC** [koishijs/koishi-plugin-blockly#21]
当前问题：缩放工作区会导致Block选择区也同步缩放
期望结果：缩放工作区，不会导致Block选择区也同步缩放
问题截图：
![1](https://user-images.githubusercontent.com/10040290/217969338-f76e35e6-570a-44b7-98d5-b56c72c0b248.jpg)
![2](https://user-images.githubusercontent.com/10040290/217969350-14f2c298-f1a3-4f57-ba78-45ae1b4219fc.jpg)

**Comment by TimeBather** [comment]
已复现，但暂时没想到什么好的解决办法，是上游Blockly的问题，也可能是特性，我明天提一个issue

**Comment by MCBBC** [comment]
> 已复现，但暂时没想到什么好的解决办法，是上游Blockly的问题，也可能是特性，我明天提一个issue

好的

**Comment by TimeBather** [comment]
似乎已经找到解决办法，预计1个major内修复

**Comment by TimeBather** [comment]
已在 b32f289 解决，此关闭Issue
