### ISSUE TITLE
我自己的原神vits接blockly，无法输出语音，报错，已装ffmpeg

### ISSUE THREAD

**Issue by yosoro11111111** [koishijs/koishi-plugin-blockly#24]
![LZIAO1HAUADN5X7%SOY9U`7](https://user-images.githubusercontent.com/124948166/218088620-b0179a99-fe63-4fd3-b70e-906364e62fbd.png)
![% K)~5AZ6U H_YBP78A`9FL](https://user-images.githubusercontent.com/124948166/218088628-74cddc51-9d87-49bb-88e0-cbca354f3a60.png)
![4@ AKX0~TTIRPCKFKYUGK](https://user-images.githubusercontent.com/124948166/218088637-7782568d-0551-4861-b9d0-d71addd4fbcc.png)
![image](https://user-images.githubusercontent.com/124948166/218088720-f3104c44-b020-4633-a894-768719209299.png)

**Comment by MCBBC** [comment]
需要这样
![QQ截图20230210201635](https://user-images.githubusercontent.com/10040290/218090538-243baa57-1060-4fea-a9cc-7bf64fb674ed.png)
而不是使用HTTP GET请求内容

**Comment by yosoro11111111** [comment]
但是我是vits请求啊，不是我的服务器固定语音

**Comment by MCBBC** [comment]
> 但是我是vits请求啊，不是我的服务器固定语音

语音这个方法包含了HTTP GET，不需要额外的使用HTTP GET方法

**Comment by yosoro11111111** [comment]
但是，我这个请求的是一个网址，然后还要再次请求网址的语音，是这样的

**Comment by MCBBC** [comment]
> 但是，我这个请求的是一个网址，然后还要再次请求网址的语音，是这样的

请问第一次请求返回的内容是什么

**Comment by MCBBC** [comment]
> 但是，我这个请求的是一个网址，然后还要再次请求网址的语音，是这样的

有没有可能blockly没办法直接获取本地的文件，你需要提供一个http链接

**Comment by yosoro11111111** [comment]
具体点，就是api返回一个C:\Users\Administrator\AppData\Local\Temp\2\tmpygr5blt2.wav

**Comment by MCBBC** [comment]
> 具体点，就是api返回一个C:\Users\Administrator\AppData\Local\Temp\2\tmpygr5blt2.wav

这种形式的链接是无法被访问的，您需要提供 http://xxx 这种形式的才可以，因为是系统限制

**Comment by yosoro11111111** [comment]
![image](https://user-images.githubusercontent.com/124948166/218093152-15911efb-ef55-462a-bb7f-bbfa954fe3c8.png)

**Comment by MCBBC** [comment]
> ![image](https://user-images.githubusercontent.com/124948166/218093152-15911efb-ef55-462a-bb7f-bbfa954fe3c8.png)

浏览器里面，可以正确的访问到文件吗

**Comment by yosoro11111111** [comment]
可以

**Comment by yosoro11111111** [comment]
http://yosoro.site:9999/file=C://Users//Administrator//AppData//Local//Temp//2//tmp8wref2yu.wav

**Comment by MCBBC** [comment]
> http://yosoro.site:9999/file=C://Users//Administrator//AppData//Local//Temp//2//tmp8wref2yu.wav

wav格式目前看来无法支持（？），请转换为mp3格式，并且按照上面方法设置后即可

**Comment by yosoro11111111** [comment]
![image](https://user-images.githubusercontent.com/124948166/218233403-f8064fbd-16ce-499f-9128-ee634edc1b57.png)
还是不行，我已经把链接变成mp3格式得了，也可以访问，koishi的onebot不能访问

**Comment by yosoro11111111** [comment]
http://yosoro.site/download?filename=tmpf4_vf08k.mp3

**Comment by TimeBather** [comment]
目前这个Issue有任何进展吗？如果没有我将会于本周末close
