### ISSUE TITLE
[Bug]无法保存

### ISSUE THREAD

**Issue by MCBBC** [koishijs/koishi-plugin-blockly#25]
当前问题：插件内容无法保存，切换至其他插件在切换回来会恢复为初始内容
期望效果：正常保存内容

**Comment by TimeBather** [comment]
好的，收到反馈，请能发一下你的代码和F12截图吗

**Comment by MCBBC** [comment]
> 好的，收到反馈，请能发一下你的代码和F12截图吗

F12无报错，代码：
![QQ截图20230210221400](https://user-images.githubusercontent.com/10040290/218113336-544eaa00-cedd-4140-98d2-9c73dfe5cb3b.png)
