### ISSUE TITLE
客户端热重载报错

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi-plugin-blockly#5]
![image](https://user-images.githubusercontent.com/33423008/216335105-7c2acc13-fde1-475c-9ed3-189ce8d5c558.png)

复现步骤：启用 devMode，修改 page.vue 后保存。出现上述报错。目前没有影响服务端的迹象，可以不修。

**Comment by TimeBather** [comment]
已经找到修复方案，下个版本应该会修复

**Comment by TimeBather** [comment]
fixed on PR #10 ，但是热重载并不推荐使用在Blockly中，且热重载会导致Blockly输出大量warning。

Blockly的副作用是重载无法消除的（他所有的Block和Extension都是注册于一个import到的对象上的），这也是这个问题的出现原因。

且我无法保证热重载后的Blockly预期运行。建议还是修改后刷新页面。

![image](https://user-images.githubusercontent.com/25410512/216510932-a20c8227-d452-4aa3-b4ae-415c57a3b217.png)
