### ISSUE TITLE
koishi深色模式下编译代码显示不全

### ISSUE THREAD

**Issue by xiecraftoffical** [koishijs/koishi-plugin-blockly#53]
![image](https://user-images.githubusercontent.com/108851959/232209890-9686f080-3b95-4f3b-b11d-3576dc5ff402.png)
![image](https://user-images.githubusercontent.com/108851959/232209902-d5a5f9d4-94f5-4b0b-8477-bcd2661f4bea.png)
如图

**Comment by TimeBather** [comment]
已在 https://github.com/koishijs/koishi-plugin-blockly/commit/8d20a8221e1805f95c9390c6949c37bd8644c485 中修复

Fixed in https://github.com/koishijs/koishi-plugin-blockly/commit/8d20a8221e1805f95c9390c6949c37bd8644c485
