### ISSUE TITLE
删除插件会触发整个客户端重新加载

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi-plugin-blockly#6]
复现流程：

1. 添加空白 block
2. 进入此 block
3. 删除此 block

此问题比较影响使用体验。怀疑背后有更严重的因素。

**Comment by TimeBather** [comment]
这个是因为删除功能目前有一些小问题（也就是删除操作，尽管前端请求了后端并在数据库中删除成功，也将新的Store数据推送给前端，但前端仍然显示该项目），怀疑和Vue的Observe机制有关，之前没有太多精力关注删除功能，所以做的临时解决方案，将会在后续版本移除

相关文件: client/page.vue#L92

**Comment by TimeBather** [comment]
已移除此问题
